services:
  bot:
    build: .
    pull_policy: build
    container_name: omnirrom-bot
    restart: unless-stopped
    environment:
      - TOKEN=${TOKEN}
      - CLIENT_ID=${CLIENT_ID}
      - GUILD_ID=${GUILD_ID}
    volumes:
      - ${DATA_PATH}:/app/data
